spring:
  main:
    allow-bean-definition-overriding: true

  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://db-svc:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: Kubernetes@1993
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
      force-content-type: true

  logging:
    level:
      org.thymeleaf: TRACE
      org.springframework.boot.autoconfigure.thymeleaf: TRACE
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus,health,metrics,info,mappings  # prometheus must be included
      base-path: /actuator  # Explicitly set base path
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m  # Scrape interval
    tags:
      application: auth-app  # Add application-level tags

# Add this security exception for Actuator
security:
  pepper:
    enabled: ${PEPPER_ENV_VAR:passwordPepper}
  filter:
    order: 0
  ignore:
    - /actuator/**
    - /actuator/prometheus